acconfig.h: add missing references
after running autoheader config.h.in is missing symbols for
x_getopt, x_opterr, x_optind, x_optopt and x_optarg which causes

| daemonize.c: In function 'usage':
| daemonize.c:123:10: warning: assignment makes pointer from integer without a cast [enabled by default]
| daemonize.c: In function 'parse_params':
| daemonize.c:205:23: error: 'x_optarg' undeclared (first use in this function)
| daemonize.c:205:23: note: each undeclared identifier is reported only once for each function it appears in
| daemonize.c:237:54: error: 'x_optopt' undeclared (first use in this function)
| daemonize.c:242:23: error: 'x_optind' undeclared (first use in this function)
| make: *** [daemonize.o] Error 1

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>